title: My Knowledge Base
author: Daniel LIOHN Ene 
email: daniel.e17@outlook.com 
description: > # this means to ignore newlines until "baseurl:"
  Static website aimed at showcasing my skills to prospective employers,
  that will also serve as a knowledge base to me.
theme: modernist

# social links
github_username:  LIOHN # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
